param(
    [string]$ConfigDir = "$env:USERPROFILE\.codex",
    [int[]]$CandidatePorts = @(7890, 7897, 7899, 10809, 10808, 8080),
    [string]$HostName = "127.0.0.1"
)

$ErrorActionPreference = "Stop"

function Test-TcpPort {
    param(
        [string]$HostName,
        [int]$Port,
        [int]$TimeoutMs = 600
    )

    $client = [System.Net.Sockets.TcpClient]::new()
    try {
        $connectTask = $client.ConnectAsync($HostName, $Port)
        if (-not $connectTask.Wait($TimeoutMs)) {
            return $false
        }

        return $client.Connected
    }
    catch {
        return $false
    }
    finally {
        $client.Dispose()
    }
}

function Find-ProxyPort {
    param(
        [string]$HostName,
        [int[]]$CandidatePorts
    )

    foreach ($port in $CandidatePorts) {
        if (Test-TcpPort -HostName $HostName -Port $port) {
            return $port
        }
    }

    return $null
}

$port = Find-ProxyPort -HostName $HostName -CandidatePorts $CandidatePorts
if ($null -eq $port) {
    $portsText = $CandidatePorts -join ", "
    throw "No local HTTP proxy was detected on $HostName. Checked ports: $portsText"
}

$proxyUrl = "http://${HostName}:$port"
$envPath = Join-Path $ConfigDir ".env"

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

$envContent = @(
    "# Generated by scripts/configure-codex-proxy.ps1"
    "# HTTPS_PROXY intentionally uses an http:// proxy URL for standard HTTP CONNECT tunneling."
    "HTTP_PROXY=$proxyUrl"
    "HTTPS_PROXY=$proxyUrl"
    "ALL_PROXY=$proxyUrl"
    "NO_PROXY=localhost,127.0.0.1,::1"
    ""
    "# Prefer standard HTTP transport and avoid WebSocket-based streaming when supported by the client."
    "CODEX_TRANSPORT=http"
    "CODEX_DISABLE_WEBSOCKET=1"
    "OPENAI_DISABLE_WEBSOCKET=1"
)

Set-Content -LiteralPath $envPath -Value $envContent -Encoding UTF8

Write-Host "Detected local HTTP proxy: $proxyUrl"
Write-Host "Wrote Codex environment file: $envPath"
